moveit/moveit_visual_tools

include/moveit_visual_tools/moveit_visual_tools.h
src/moveit_visual_tools.cpp

currently end-effector markers are based on the default robot state (ie all zero),
this allows passing a vector of doubles for all active joint in the end-effector group
Passing a new set of joint values will invalidate the cache but for our use-case this is
neglectible and could be optimized later
implements #18

Allow setting joint values for end-effector marker

---

CMakeLists.txt
package.xml
src/moveit_visual_tools.cpp

All conversions from `eigen_conversions` are now using `tf2_eigen` instead. `tf::TransformListener` is now converted to a combination of `tf2_ros::Buffer` and `tf2_ros::TransformListener`.
These **changes are for `melodic-devel` only**, and depend on https://github.com/ros-planning/moveit/pull/830.

tf2 migration

---

src/moveit_visual_tools.cpp

We are currently investigating a massive slowdown in our code after some changes that should have led to speedups. One of the sources is that moveit_visual_tools triggers to many full updates in PlanningSceneMonitor. Another one is that it calls ros::spinOnce() afterwards, processing those updates directly in this thread (instead of a separate async spinner thread.
- triggering UPDATE_SCENE leads to sending a full planning scene including all meshes. For all use-cases in this lib UPDATE_GEOMETRY is sufficient and sends only diffs
- calling ros::spinOnce() in random places messes up the event queue (e.g. joint state updates being processed in gui thread instead of the async spinner thread)

triggering UPDATE_GEOMETRY is sufficient, dont spinOnce

---

include/moveit_visual_tools/moveit_visual_tools.h
src/moveit_visual_tools.cpp

Additional visualization

---

include/moveit_visual_tools/moveit_visual_tools.h
src/moveit_visual_tools.cpp

the cherry-picked in commit used tf which is not supported in melodic.  This PR updates the function call to use tf2 methods.

Fixing melodic branch 

---

include/moveit_visual_tools/moveit_visual_tools.h
src/moveit_visual_tools.cpp

Clang formatting and renaming a variable for consistency

Running clang and fixing variable names

---

src/imarker_robot_state.cpp
src/moveit_visual_tools.cpp

Follows new style http://moveit.ros.org/documentation/contributing/code/

Switch to LOGNAME style re:moveit

---

src/imarker_end_effector.cpp
src/imarker_robot_state.cpp

See https://github.com/ros-planning/moveit/pull/1288

Remove attempts from setFromIK

---

include/moveit_visual_tools/moveit_visual_tools.h
src/moveit_visual_tools.cpp

The current implementation of `publishRobotState()` allows coloring all links with a specific color.
This PR adds an optional argument `highlight_links` for specifying only a set of link names that should be highlighted with the given color. One example scenario would be to highligh links if they are in collision.
I'm also thinking of adding another function `visualizeCollisionResult()` or even `checkCollision()` that runs a collision check and then highlights the colliding links and publishes contact points using `publishContactPoints()`.
**UPDATE** - I extended this PR
* adds `checkAndPublishCollision()` for performing collision checks and highlighting the results
* adds publishContactPoints() that allows passing `CollisionResult::ContactMap` which allows visualizing contact points for …

Highlight selected links in publishRobotState() + improved collision visualization

---

include/moveit_visual_tools/moveit_visual_tools.h
src/moveit_visual_tools.cpp

This exposes the robot state and trajectory path publishers so that the user can publish their own msgs through the moveit_visual_tools publishers

exposing the publishers to the user

---

src/moveit_visual_tools.cpp

When visualizing trajectories of subgroups the previous implementation would use the shared initial robot state for populating the joint values outside the group. This can have strange effects like apparent link collisions even though the original trajectory is collision free. If we have a robot trajectory with fully populated robot states we should use these instead.

Use first trajectory point as start state for visualization

---

include/moveit_visual_tools/moveit_visual_tools.h
src/moveit_visual_tools.cpp

- Do not change the default color to clear
- Addresses issues in moveit_grasps
- Minor cleanup
Reverts a change in https://github.com/ros-planning/moveit_visual_tools/pull/21/

Fix for missing end effector markers because clear

---

src/moveit_visual_tools.cpp

This pull request should fix #52 after [pull request #55](https://github.com/ros-planning/moveit_msgs/pull/55) get merged.
@davetcoleman 
@henningkayser

Update hideRobot to hide visualized robot state by setting hide_display in DisplayRobotState msg

---

.travis.yml

Alternative to #57: Due to incompatible `moveit_msgs`, the master branch cannot compile on Kinetic and Melodic anymore.

Drop melodic + kinetic support for master branch

---

src/imarker_end_effector.cpp
src/imarker_robot_state.cpp

This PR adapts the visual tools for the unified collision environment as proposed [here](https://github.com/ros-planning/moveit/pull/1584). It changes `getCollisionWorld` to the new `getCollisionEnv` function.
This does not build as the main unified PR has to be merged together with this.

[WIP] Unified collision environment

---

include/moveit_visual_tools/imarker_end_effector.h
src/imarker_robot_state.cpp

IMarkerEndEffector has a vectorizable Eigen member, so it needs proper alignment.
`std::make_shared` also does not respect alignment, so it is replaced with `std::allocate_shared`.

Fix Eigen alignment

---

src/imarker_end_effector.cpp

tf_conversions was still in use in one compilation unit

Replace tf_conversions with tf2::convert

---

CMakeLists.txt

This is for a Noetic release.  This is because Noetic is the last ROS1 version and it will enable us to increase the version of the library for future releases.

[maint] add soname version

---

include/moveit_visual_tools/moveit_visual_tools.h
src/moveit_visual_tools.cpp

Sadly, MoveItVisualTools(std::string) is already defined and
requires a *base_link*. In my opinion rather unfortunate, because the
topic seems much more likely to change, but that's what we got.
Instead, I opted for a constructor with hard-coded topic name.
Experienced users that need to change the topic should already know
the name of their base link.
Makes sense to backport to `melodic-devel`.
Fixes #23

provide a parameter-less constructor for new users

---

include/moveit_visual_tools/imarker_end_effector.h
src/imarker_end_effector.cpp

Related to https://github.com/ros-planning/moveit/pull/2792 .
Addresses this clang warning
<<<
moveit_visual_tools/include/moveit_visual_tools/imarker_end_effector.h:150:29: error: private field 'color_' is not used [-Werror,-Wunused-private-field]
rviz_visual_tools::colors color_ = rviz_visual_tools::PURPLE;
^
1 error generated.
>>>
We could have removed the member just as well (it barely matters...),
but that would entail an unnecessary API change in the constructor.
I added the default value for the constructor parameter as it is always overwritten until now...

use specified color_ for EndEffector marker

---

.github/workflows/industrial_ci_action.yaml

Our ccache is broken in CI, thus our ccache action should be updated to match Github's new ccache action v2 as per https://github.com/ros-planning/moveit2/pull/619

Fix ccache

---

src/moveit_visual_tools.cpp

Fixed possible nullpointer segfault

---

CMakeLists.txt

When i include **moveit_visual_tools** as a dependency (in particular as a dependency of **movit2_tutorials**), cmake complains about  not finding the library `moveit_visual_tools_demo`.
This should fix the issue.

Don't export moveit_visual_tools_demo as a dependency

---

moveit_visual_tools.repos

We should use ros2 branch of rviz_visual_tools in ros2 branch of mvt and open a foxy branch for mvt that depends on foxy branch of rvt.

Update rviz_visual_tools branch

---

.pre-commit-config.yaml

Running pre-commit with the current black version is broken, and should be updated as per https://github.com/ros-planning/moveit2/pull/1148

[master] Update black version

---

src/moveit_visual_tools.cpp

If a joint model group doesn't define an end-effector, 'publishTrajectoryLine' can't create and publish the markers. But it would still succeed. This change adds a check for missing end-effectors, logs a warning and returns false, since markers can't be published.

Return error in publishTrajectoryLine if no end-effectors are defined

---

include/moveit_visual_tools/moveit_visual_tools.h

The default empty string would result in a runtime exception, which can't even be fixed by updating the topic name.

Default state publisher topic to DISPLAY_ROBOT_STATE_TOPIC
