README.md

It didn't reflect the changes in Indigo yet

Updated link to Doxygen API description

---

README.md

I think it's hard to see the currently layout on readme.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/davetcoleman/moveit_visual_tools/7)

fix the how to link a demo img

---

include/moveit_visual_tools/imarker_robot_state.h
src/imarker_end_effector.cpp
src/imarker_robot_state.cpp
src/moveit_visual_tools.cpp

Divided into clean commits:
- Improve console output
- imarker: Fix setToRandomState()
- Small threading fixes
- Ability to specify clearance for random state
@mlautman

Various improvements needed while finishing my thesis

---

.clang-format
include/moveit_visual_tools/imarker_end_effector.h
include/moveit_visual_tools/imarker_robot_state.h
include/moveit_visual_tools/moveit_visual_tools.h
src/imarker_end_effector.cpp
src/imarker_robot_state.cpp
src/moveit_visual_tools.cpp

Applied MoveIt!'s .clang-format
Merge https://github.com/ros-planning/moveit_visual_tools/pull/16 first
@mlautman

Kinetic code format

---

src/moveit_visual_tools.cpp

by request of https://github.com/ros-planning/moveit_visual_tools/pull/29

No spinOnce when triggering

---

CMakeLists.txt
package.xml

Should be cherry-picked to melodic

Fixup CMakeLists and package.xml

---

MIGRATION.md
include/moveit_visual_tools/imarker_end_effector.h
include/moveit_visual_tools/imarker_robot_state.h
include/moveit_visual_tools/moveit_visual_tools.h
src/imarker_end_effector.cpp
src/imarker_robot_state.cpp
src/moveit_visual_tools.cpp
src/moveit_visual_tools_demo.cpp

See https://github.com/ros-planning/moveit/pull/1096
Must be merged at the same time as moveit's

Fix Eigen::Affine3d for Melodic (using Eigen::Isometry3d)

---

.travis.yml
include/moveit_visual_tools/imarker_end_effector.h
include/moveit_visual_tools/imarker_robot_state.h
include/moveit_visual_tools/moveit_visual_tools.h
moveit.rosinstall
src/imarker_end_effector.cpp
src/imarker_robot_state.cpp
src/moveit_visual_tools.cpp

Use moveit repo's travis config

---

moveit.rosinstall

use master branch for all deps

---

include/moveit_visual_tools/moveit_visual_tools.h

This was properly implemented a while ago

update doc of hideRobot()

---

include/moveit_visual_tools/imarker_end_effector.h
include/moveit_visual_tools/imarker_robot_state.h
include/moveit_visual_tools/moveit_visual_tools.h
src/moveit_visual_tools.cpp

Per https://github.com/ros-planning/moveit/pull/2135

Replace robot_model and robot_state namespaces by moveit::core

---

src/imarker_end_effector.cpp

[melodic-devel] Replace tf_conversions with tf2's toMsg / fromMsg (#66)

---

CHANGELOG.rst
package.xml

Here are the changelogs curated to be easy to understand the latest changes going into the release.

Changelogs for Noetic 3.6.0

---

package.xml

Fix typo in package.xml

---

.github/workflows/build_and_test.yaml

Fixes the cache prefix causing #100 to fail.

Fix cache prefix

---

src/moveit_visual_tools.cpp

Remove spin some

---

CMakeLists.txt
CONTRIBUTING.md
LICENSE
include/moveit_visual_tools/imarker_end_effector.h
include/moveit_visual_tools/imarker_robot_state.h
include/moveit_visual_tools/moveit_visual_tools.h
launch/demo_rviz.launch.py
package.xml
src/imarker_end_effector.cpp
src/imarker_robot_state.cpp
src/moveit_visual_tools.cpp
src/moveit_visual_tools_demo.cpp

To unblock the [galactic](https://github.com/ros/rosdistro/pull/30882) & [rolling](https://github.com/ros/rosdistro/pull/30883) releases

Generate license using ament_copyright

---

src/moveit_visual_tools.cpp

Fixes the warnings when building from #107

Fixed deprecated call to PlanningSceneMonitor's constructor

---

.pre-commit-config.yaml
src/imarker_end_effector.cpp
src/imarker_robot_state.cpp

Updates clang-format to 12 and adds minor fix for Jammy.

Jammy fixes and clang-format-12

---

.github/workflows/format.yaml
.github/workflows/industrial_ci_action.yaml
.pre-commit-config.yaml
src/moveit_visual_tools.cpp

publishTrajectoryLine(): issue error when no end-effector tips are found

---

src/moveit_visual_tools.cpp

Self explanatory, subsribe->subscribe.

Fix typo in warning message
